name: "Bug Report"
description: Create a report to let us know about an issue with the mod
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
- type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Winblows 10/11
        - Linux
      default: 0
    validations:
      required: true
- type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Is this an issue occuring with a game client or a dedicated server (or both)
      options:
        - Single Player
        - P2P Host (You are hosting a game locally and letting your friends join)
        - P2P Client (You are connecting to your friend's game)
        - Client (You are connecting to a dedicated server)
        - Server (You are either self hosting one or pay to have one hosted in the cloud with a service like ShockByte)
      default: 0
    validations:
      required: true
- type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Describe what happened when the bug occured.
      placeholder: Tell us what you see!
    validations:
      required: true      
- type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: It should have...
    validations:
      required: true          
